In [1]:
import torch
import numpy as np


1.1、直接初始化
    tensor可以直接从数据中创建。
    数据类型是自动推断出来的。

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

1.2、可以从Numpy中创建tensor

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

1.3、从其他tensor中初始化
    新的tensor保留了参数tensor的属性（形状、数据类型），除非明确重写。

In [4]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0652, 0.7916],
        [0.5088, 0.1966]]) 



1.4、使用随机数和常数初始化
    shape是一个元组。在下面的代码中，它决定了输出tensor的维度。

In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")


Random Tensor: 
 tensor([[0.3058, 0.2309, 0.0910],
        [0.1161, 0.5874, 0.9353]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


2.1、tensor的性质
    tensor属性描述了它们的
        形状；
        数据类型；
        存储它们的设备。

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


3、tensor的操作
    100多种tensor操作，包括算术、线性代数、矩阵操作（转置、索引、切片）、采样等。
    这些操作中的每一个都可以在GPU上运行（速度通常比在CPU上高）。
    默认情况下，tensor是在CPU上创建的。我们需要使用.to方法明确地将tensor移动到GPU上（在检查GPU的可用性之后）。

In [7]:
# 如果有的话，我们把我们的tensor移到GPU上
if torch.cuda.is_available():
    tensor = tensor.to('cuda')


3.1、标准的类似numpy的索引和切分

In [11]:
tensor = torch.ones(4, 4) # 二维的

'''
data = [[1, 2,3,4],
        [5, 6,7,8],
        [9,10,11,12],
        [13,14,15,16],]
tensor = torch.tensor(data)
'''
print('第一行: ', tensor[0])
print('第一列：', tensor[:, 0])
print('最后一列：', tensor[..., -1])
print('让某一列全为0：')
tensor[:,1] = 0
print(tensor)


第一行:  tensor([1., 1., 1., 1.])
第一列： tensor([1., 1., 1., 1.])
最后一列： tensor([1., 1., 1., 1.])
让某一列全为0：
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


3.2、连接tensor
    可以使用torch.cat沿着给定的维度连接多个tensor。
    也请看torch.stack，它是另一个与torch.cat有细微差别的tensor连接操作。
    cat全称是concatnate,其中con是前缀，所以取cat代指concatenate

In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
t0 = torch.cat([tensor, tensor, tensor], dim=0)
print(t0)


tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


3.3、算术运算
    1 矩阵乘法,对应的行列元素相乘再相加
        A=a11 a12 a13   B=b11 b12   a11b11+a12b21+a13b31  a11b12+a12b22+a13b32
          a21 a22 a23     b21 b22   a21b11+a22b21+a23b31  a21b12+a22b22+a23b32
                          b31 b32
    2 矩阵元素相乘，对应位置的元素相乘
        如：A= a11 a12 a13   B=b11 b12 b13   a11b11 a12b12 a13b13
              a21 a22 a23     b21 b22 b23   a21b21 a22b22 a23b23

In [18]:
# y1 y2 y3 的值相同，都是矩阵乘法的结果
tensor = torch.ones(4, 4)
y1 = tensor @ tensor

y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor,tensor.T,out=y3)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [27]:
# 矩阵元素相乘
data = [[1, 2,3,4],
        [5, 6,7,8],
        [9,10,11,12],
        [13,14,15,16],]
tensor2 = torch.tensor(data)
z1 = tensor*tensor2

z2 = tensor.mul(tensor2)

z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor2,out=z3)

print(tensor,'\n',tensor2,'\n',z3)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]) 
 tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
